name: Unit Tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g npm
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: npm test